# Generated by Django 4.1.3 on 2023-01-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='کارمند سایت  '),
        ),
    ]
