# Generated by Django 4.1.3 on 2023-01-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(null=True, verbose_name='آدرس گیت هاب'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(null=True, verbose_name='آدرس اینستاگرام'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(null=True, verbose_name='آدرس لینکدین'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(null=True, verbose_name='آدرس توییتر'),
        ),
    ]
