# Generated by Django 4.1.3 on 2023-01-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_user_github_user_instagram_user_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, default=1, verbose_name='آدرس گیت هاب'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, default=1, verbose_name='آدرس اینستاگرام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, default=1, verbose_name='آدرس لینکدین'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, default=1, verbose_name='آدرس توییتر'),
            preserve_default=False,
        ),
    ]
