# Generated by Django 4.1.3 on 2022-11-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_alter_generalnotification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال در '),
        ),
        migrations.AlterField(
            model_name='personalnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال در '),
        ),
    ]
