# Generated by Django 4.1.3 on 2023-01-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beteacher',
            name='name',
        ),
        migrations.AddField(
            model_name='beteacher',
            name='fullname',
            field=models.CharField(default=1, max_length=20, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
    ]
