# Generated by Django 4.1.3 on 2023-02-26 14:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان دسته بندی مرجع ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد در ')),
            ],
            options={
                'verbose_name': 'دسته بندی مرجع',
                'verbose_name_plural': 'دسته بندی های مرجع ',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان دسته بندی ')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت ')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='آدرس اسلاگ ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد در ')),
                ('category', models.ManyToManyField(related_name='subcategories', to='Video.category', verbose_name='زیرمجموعه دسته بندی ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ویدیو')),
                ('video', models.FileField(upload_to='videos/', verbose_name='آپلود ویدیو')),
                ('description', ckeditor.fields.RichTextField(verbose_name='درباره ویدئو')),
                ('video_cover', models.ImageField(upload_to='banner', verbose_name='بنر ویدیو')),
                ('time', models.CharField(blank=True, max_length=15, null=True, verbose_name='تایم ویدیو')),
                ('likes_count', models.BigIntegerField(default=0, verbose_name='تعداد لایک ها')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='آدرس اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار در ')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی در ')),
                ('category', models.ManyToManyField(related_name='videos', to='Video.subcategory', verbose_name='دسته بندی ویدیو')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='منتشر کننده')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت در')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Video.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'لایک ',
                'verbose_name_plural': 'لایک ها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت در')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Video.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'علاقه مندی ',
                'verbose_name_plural': 'علاقه مندی ها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن کامنت ')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Video.comment', verbose_name='زیرمجموعه')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Video.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ('-created_at',),
            },
        ),
    ]
