# Generated by Django 4.1.7 on 2023-05-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت (ریال)'),
        ),
    ]
