# Generated by Django 4.1.1 on 2022-10-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در '),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/', verbose_name='آپلود ویدیو'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_cover',
            field=models.ImageField(upload_to='banner', verbose_name='بنر ویدیو'),
        ),
    ]
