# Generated by Django 4.1.1 on 2022-10-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0002_alter_comment_created_at_alter_video_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
    ]
