# Generated by Django 4.1.3 on 2022-11-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0003_remove_video_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='about_video',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
