# Generated by Django 4.1.3 on 2023-01-09 18:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0005_rename_caption_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='درباره ویدئو'),
        ),
    ]
