# Generated by Django 4.1.3 on 2023-01-17 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Video', '0007_video_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت در')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Video.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'لایک ',
                'verbose_name_plural': 'لایک ها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
