# Generated by Django 4.1.3 on 2023-01-17 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Video', '0008_like_delete_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت در')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Video.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'علاقه مندی ',
                'verbose_name_plural': 'علاقه مندی ها',
                'ordering': ('-created_at',),
            },
        ),
    ]
